spring:
  application:
    name: bottle-note-admin
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /
