spring:
  # 애플리케이션 이름
  application:
    name: bottlenote-admin

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    root: INFO
    com.bottlenote: DEBUG
